/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/BeoJtMI3Q2z
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

 import { Inter } from 'next/font/google'

 inter({
  subsets: ['latin'],
  display: 'swap',
})

 To read more about using these font, please visit the Next.js documentation:
 - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
 - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
 **/
import {Logo} from "@/components/component/logo";
import {SearchComponent} from "@/components/component/searchComponent";
import {BookColumn} from "@/components/component/bookColumn";

export function Component() {
  return (
    <div>
      <header className="flex items-center justify-between h-16 px-6 border-b">
        <Logo/>
        <SearchComponent/>
      </header>
      <div className="container mx-auto py-12 ml-4">
        <div className="grid grid-cols-3 gap-8">
          <BookColumn name={"library"} query={null}/>
          <BookColumn name={"kyobo"} query={null}/>
          <BookColumn name={"interpark"} query={null}/>
        </div>
      </div>
    </div>
  )
}

